### ISSUE TITLE
Нестыковка

### ISSUE THREAD

**Issue by LiFeAiR** [yandex/ymaps-pie-chart-clusterer#2]
ymaps-pie-chart-clusterer/src/pieChartClusterer/icon/colors.js
не состыкован с стилями библиотеки islands хотя и использует его
пример:
pieChartClusterer: 'blue', 'red', 'darkOrange', 'night', 'darkBlue', 'pink', 'gray', 'brown', 'darkGreen', 'violet', 'black', 'yellow', 'green', 'orange', 'lightBlue', 'olive';
islands: 'blue', 'red', 'darkorange', 'night', 'darkblue', 'pink', 'grey', 'brown', 'darkgreen', 'violet', 'black', 'yellow', 'green', 'orange', 'lightblue', 'olive';

**Comment by dimik** [comment]
Ключи стилей не чувствительны к регистру

**Comment by twirl** [comment]
Неправда, чувствительны. В islands просто все варианты забиты — и camelCase, и plain. camelCase предпочтительнее.

**Comment by LiFeAiR** [comment]
эти ключи тоже состыкованы?
pieChartClusterer: 'gray'
islands: 'grey'

**Comment by twirl** [comment]
Да.
