### ISSUE TITLE
Wrong placemark color and type for single markers

### ISSUE THREAD

**Issue by Sett** [yandex/ymaps-pie-chart-clusterer#3]
1. I am using two colors: red and green (twirl#redDotIcon and twirl#greenDotIcon).
2. If placemarks appeared in a cluster, than color and type is wright.
3. If placemarks become single, than color is blue without a dot inside.

**Comment by twirl** [comment]
In API 2.1 'twirl#' prefix is deprecated, use 'islands#' instead.

**Comment by Sett** [comment]
It is very strange to change such important things, which are broke back compatabilities in a minor versions...

**Comment by twirl** [comment]
2.1 is *major* version, it breaks compatibility in several areas
https://tech.yandex.ru/maps/doc/jsapi/2.1/update/concepts/update-docpage/#update-2.0
https://tech.yandex.ru/maps/doc/jsapi/2.1/versions/concepts/index-docpage/
We don't use semver since Yandex Maps API is simply older than semver.
