### ISSUE TITLE
Кластеры сломались

### ISSUE THREAD

**Issue by ilson-** [yandex/ymaps-pie-chart-clusterer#4]
Добрый день! У меня на рабочей системе вдруг кластеры стали не отображатья. Демо тоже перестало работать. Видимо в api что-то сменили и всё накрылось?

**Comment by twirl** [comment]
Дайте ссылку на страницу, пожалуйста.

**Comment by ilson-** [comment]
Ваша демка http://yandex.github.io/ymaps-pie-chart-clusterer/

**Comment by twirl** [comment]
@dimik Там версию API не надо поднять в примере часом?

**Comment by dimik** [comment]
Спасибо за сообщение, пример починили
